### PR TITLE
Remove poetry and move to rye

### PR DESCRIPTION
**Pull request by andrewram4287**

### CODE REVIEW

**Comment by andrewram4287** [comment]
@aarmey I didn't know if there was a rye equivalent for this line

```
testprofile:
poetry run python3 -m cProfile -o profile -m pytest -s -x -v
gprof2dot -f pstats --node-thres=1.0 profile | dot -Tsvg -o profile.svg
```

**Comment by aarmey** [comment]
Added the changes to make it work.

**Comment by andrewram4287** [comment]
@aarmey Awesome looks its running successfully now! 

Did you want to address the errors or would you like me to?

**Comment by aarmey** [comment]
I'll take care of these!

**Comment by aarmey** [comment]
There are a lot of false positives from pyright, so I'm just going to disable its check during the build.

**Pull request merged**
